# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-07 19:43
from __future__ import unicode_literals

from django.db import migrations
import private_storage.fields
import private_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='agenda',
            field=private_storage.fields.PrivateFileField(default='', storage=private_storage.storage.PrivateStorage(), upload_to='meetings'),
            preserve_default=False,
        ),
    ]
